safec: Define _GNU_SOURCE
musl does not define this variable automatically but safec does provide
wrapper for some GNU extentions as well e.g.

error: implicit declaration of function 'localtime_r' is invalid in C99

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit c93f66d65a333dee1bd7b8dbb776ceedc715cf86)