python3-m2crypto: Upgrade 0.42.0 -> 0.44.0
Changelog: https://gitlab.com/m2crypto/m2crypto/-/tags

The cmd will be None after introduced the commit [1] in the new
version and result the below do_compile error.
 DEBUG: Executing shell function do_compile
 * Getting build dependencies for wheel...
 [snip]
 TypeError: expected str, bytes or os.PathLike object, not NoneType
 ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel

So make the cmd available to fix the above issue.

[1] https://gitlab.com/m2crypto/m2crypto/-/commit/4d7880b019a67e24458b1c9a50331c18c9eec827

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>