gperftools: fix do_compile failure for qemuppc
Fix the following error for qemuppc.

  error: 'siginfo_t' does not name a type

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
(cherry picked from commit 02cf7aba3c06ffc3c1904e930eeb4387e81aa168)