miniupnpd: Build config.h before full build
This fixes a race condition e.g.

testminissdp.c:15:10: fatal error: config.h: No such file or directory
   15 | #include "config.h"
      |          ^~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'testminissdp.o' failed

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 9429dba394182d69babe3326f78211cbd2d695ba)